In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\uniao\OneDrive\Área de Trabalho\Cursos 2024\EDA - VIDEO GAME SALES\database\vgsales.xlsx")
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,2025-08-29 00:00:00,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,2025-01-11 00:00:00,3.28,2.96,33
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1,31.37

In [3]:
# Contagem dos valores nulos nas colunas
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [4]:
# Contagem total dos valores nulos
df.isnull().sum().sum()

329

In [5]:
# Laço FOR para calcular a porcentagem de valores nulos/vazios por coluna
total_linhas = len(df)

print("Porcentagem de valores nulos/vazios por coluna:\n")

for coluna in df.columns:
    nulos = df[coluna].isnull().sum()
    vazios = (df[coluna] == '').sum()
    total_faltantes = nulos + vazios
    percentual = (total_faltantes / total_linhas) * 100
    print(f"{coluna}: {percentual:.2f}%")

Porcentagem de valores nulos/vazios por coluna:

Rank: 0.00%
Name: 0.00%
Platform: 0.00%
Year: 1.63%
Genre: 0.00%
Publisher: 0.35%
NA_Sales: 0.00%
EU_Sales: 0.00%
JP_Sales: 0.00%
Other_Sales: 0.00%
Global_Sales: 0.00%

In [65]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,2025-08-29 00:00:00,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,2025-01-11 00:00:00,3.28,2.96,33
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0,0,0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0,0,0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0,0,0,0,0.01
16596,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0,0.01,0,0,0.01
16597,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0,0,0,0.01

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16327 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16327 non-null  int64
 1   Name          16327 non-null  object
 2   Platform      16327 non-null  object
 3   Year          16327 non-null  int32
 4   Genre         16327 non-null  object
 5   Publisher     16291 non-null  object
 6   NA_Sales      16327 non-null  object
 7   EU_Sales      16327 non-null  object
 8   JP_Sales      16327 non-null  object
 9   Other_Sales   16327 non-null  object
 10  Global_Sales  16327 non-null  object
dtypes: int32(1), int64(1), object(9)
memory usage: 1.4+ MB

In [58]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,2025-08-29 00:00:00,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,2025-01-11 00:00:00,3.28,2.96,33
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0,0,0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0,0,0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0,0,0,0,0.01
16596,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0,0.01,0,0,0.01
16597,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0,0,0,0.01

In [22]:
df.to_csv(f"gameSales2.csv", index=False)

In [23]:
from google.cloud import storage
import os

In [29]:
service_account_path = r"C:\Users\uniao\OneDrive\Área de Trabalho\Cursos 2024\EDA - VIDEO GAME SALES\bucket\gamersales-18c83726cb0f.json"
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = service_account_path

In [25]:
bucket_name = "ad13grupo04"
folder_name = "Tratados/"
local_file = "gameSales2.csv"

client = storage.Client()
bucket = client.bucket(bucket_name)

destination_blob_name = f"{folder_name}{local_file}"
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(local_file)

print(f"Arquivo enviado para: gs://{bucket_name}/{destination_blob_name}")

Arquivo enviado para: gs://ad13grupo04/Tratados/gameSales2.csv

In [28]:
from google.cloud import bigquery


service_account_path = r"C:\Users\uniao\OneDrive\Área de Trabalho\Cursos 2024\EDA - VIDEO GAME SALES\bucket\gamersales-edae4d5f7170.json"
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = service_account_path

client = bigquery.Client()

project = 'gamersales'
client = bigquery.Client(project)
project_id = project
dataset_id = f"{project_id}.gameSales"


dataset = bigquery.Dataset(dataset_id)
dataset.location = "us-west1"


dataset = client.create_dataset(dataset, exists_ok=True)
print(f"Dataset {dataset_id} criado com sucesso!")


tabela_destino = 'gameSales.gameSales2'
etl = client.load_table_from_dataframe(df, tabela_destino)
etl.result()
print("Dados enviados com sucesso para o BigQuery!")

ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)

In [71]:
!pip install pandas gcsfs

Requirement already satisfied: pandas in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (2.1.4)
Collecting gcsfs
  Downloading gcsfs-2025.3.2-py2.py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\uniao\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.4)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from gcsfs)
  Downloading aiohttp-3.11.16-cp311-cp311-win_amd64.whl.metadata (8.0 kB)
Requirement already satisfied: decorator>4.1.2 in c:\users\uniao\appdata\roaming\python\python311\site-packages (from gcsfs) (5.1.1)
Collecting fsspec==2025.3.2 (from gcsfs)
  Downloading fsspec-2025.3.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: google-auth>=1.2 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from gcsfs) (2.38.0)
Collecting google-auth-oauthlib (from gcsfs)
  Downloading google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: google-cloud-storage in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from gcsfs) (3.1.0)
Requirement already satisfied: requests in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from gcsfs) (2.31.0)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs) (25.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs)
  Downloading frozenlist-1.5.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs)
  Downloading multidict-6.4.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs)
  Downloading propcache-0.3.1-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs)
  Downloading yarl-1.20.0-cp311-cp311-win_amd64.whl.metadata (74 kB)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=1.2->gcsfs) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=1.2->gcsfs) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=1.2->gcsfs) (4.9)
Requirement already satisfied: six>=1.5 in c:\users\uniao\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib->gcsfs)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.15.0 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage->gcsfs) (2.24.1)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.4.2 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage->gcsfs) (2.4.2)
Requirement already satisfied: google-resumable-media>=2.7.2 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage->gcsfs) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-cloud-storage->gcsfs) (1.6.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from requests->gcsfs) (2023.11.17)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs) (1.69.1)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs) (5.29.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage->gcsfs) (1.26.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in c:\users\uniao\appdata\local\programs\python\python311\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs) (0.6.1)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs)
  Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Downloading gcsfs-2025.3.2-py2.py3-none-any.whl (36 kB)
Downloading fsspec-2025.3.2-py3-none-any.whl (194 kB)
Downloading aiohttp-3.11.16-cp311-cp311-win_amd64.whl (442 kB)
Downloading google_auth_oauthlib-1.2.1-py2.py3-none-any.whl (24 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Downloading frozenlist-1.5.0-cp311-cp311-win_amd64.whl (51 kB)
Downloading multidict-6.4.3-cp311-cp311-win_amd64.whl (38 kB)
Downloading propcache-0.3.1-cp311-cp311-win_amd64.whl (45 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading yarl-1.20.0-cp311-cp311-win_amd64.whl (93 kB)
Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
Installing collected packages: propcache, oauthlib, multidict, fsspec, frozenlist, aiohappyeyeballs, yarl, requests-oauthlib, aiosignal, google-auth-oauthlib, aiohttp, gcsfs
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.11.16 aiosignal-1.3.2 frozenlist-1.5.0 fsspec-2025.3.2 gcsfs-2025.3.2 google-auth-oauthlib-1.2.1 multidict-6.4.3 oauthlib-3.2.2 propcache-0.3.1 requests-oauthlib-2.0.0 yarl-1.20.0

In [ ]:
import os

# Substitua pelo caminho do seu arquivo JSON
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"C:\Users\uniao\OneDrive\Área de Trabalho\Cursos 2024\EDA - VIDEO GAME SALES\bucket\gamersales-18c83726cb0f.json"

In [ ]:
!pip install pandas gcsfs

In [78]:
import pandas as pd
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"C:\Users\uniao\OneDrive\Área de Trabalho\Cursos 2024\EDA - VIDEO GAME SALES\bucket\gamersales-18c83726cb0f.json"

csv_path = 'gs://ad13grupo04/Tratados/GameSales.csv'


df = pd.read_csv(csv_path)
df.head()

,Ranking,Nome,Plataforma,Ano_Lancamento,Genero,Publicadora,Vendas_AmericaNorte,Vendas_Europa,Vendas_Japao,Vendas_Outros,Vendas_Mundial
0,1,Wii Sports,Nintendo Wii,2006-01-01,Esportes,Nintendo,41490000,29020000,3770000,8460000,82740000
1,2,Super Mario Bros.,NES,1985-01-01,Plataforma,Nintendo,29080000,3580000,6810000,770000,40240000
2,3,Mario Kart Wii,Nintendo Wii,2008-01-01,Corrida,Nintendo,15850000,12880000,3790000,3310000,35820000
3,4,Wii Sports Resort,Nintendo Wii,2009-01-01,Esportes,Nintendo,15750000,11010000,3280000,2960000,33000000
4,5,Pokemon Red/Pokemon Blue,Game Boy,1996-01-01,Jogo de representação,Nintendo,11270000,8890000,10220000,1000000,31370000